/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from './test/index.js';
export { IODPRegistry__factory } from './IODPRegistry__factory.js';
export { ODPAuthorAttestation__factory } from './ODPAuthorAttestation__factory.js';
export { ODPEditionUnits__factory } from './ODPEditionUnits__factory.js';
export { ODPHosting__factory } from './ODPHosting__factory.js';
export { ODPPassportConcerns__factory } from './ODPPassportConcerns__factory.js';
export { ODPPassportProofRegistry__factory } from './ODPPassportProofRegistry__factory.js';
export { ODPProfileDirectory__factory } from './ODPProfileDirectory__factory.js';
export { ODPRegistryRelations__factory } from './ODPRegistryRelations__factory.js';
export { ODPSatellite__factory } from './ODPSatellite__factory.js';
export { ODPStatementJournal__factory } from './ODPStatementJournal__factory.js';
export { ODPWalletDocumentAnchor__factory } from './ODPWalletDocumentAnchor__factory.js';
export { ObjectDigitalPassport__factory } from './ObjectDigitalPassport__factory.js';
