/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ODPSatellite, ODPSatelliteInterface } from "../ODPSatellite.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "code",
        "type": "uint16"
      }
    ],
    "name": "EC",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "odpRegistry",
    "outputs": [
      {
        "internalType": "contract IODPRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class ODPSatellite__factory {
    static readonly abi = _abi;
    static createInterface(): ODPSatelliteInterface {
      return new Interface(_abi) as ODPSatelliteInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ODPSatellite {
      return new Contract(address, _abi, runner) as unknown as ODPSatellite;
    }
  }
  