/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { ODPTestWallet, ODPTestWalletInterface } from "../../test/ODPTestWallet.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "target",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "data",
        "type": "bytes"
      }
    ],
    "name": "execute",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60a0806040523461002357336080526101bf90816100288239608051816101050152f35b5f80fdfe60806040526004361015610011575f80fd5b5f803560e01c631cff79cd14610025575f80fd5b346100a15760403660031901126100a1576004356001600160a01b03811681036100a4576001600160401b0391602435908382116100a157366023830112156100a15781600401359384116100a15736602485840101116100a15761009d610091856024850186610103565b604051918291826100a8565b0390f35b80fd5b5080fd5b602080825282518183018190529093925f5b8281106100db57505060409293505f838284010152601f8019910116010190565b8181018601518482016040015285016100ba565b634e487b7160e01b5f52604160045260245ffd5b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031633036101ae578260405193849384378201905f93848094848280965203925af13d156101a5576001600160401b033d8181116101a05760405191601f8201601f19908116603f01168301908111838210176101a0576040528152809260203d92013e5b156101985790565b602081519101fd5b6100ef565b60609150610190565b5f80fdfea164736f6c6343000814000a";

  
      type ODPTestWalletConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ODPTestWalletConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ODPTestWallet__factory extends ContractFactory {
    
      constructor(...args: ODPTestWalletConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ODPTestWallet & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ODPTestWallet__factory {
      return super.connect(runner) as ODPTestWallet__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ODPTestWalletInterface {
      return new Interface(_abi) as ODPTestWalletInterface;
    }
    
    override attach(address: string | Addressable): ODPTestWallet {
      return super.attach(address) as ODPTestWallet;
    }
  static connect(address: string, runner?: ContractRunner | null): ODPTestWallet {
      return new Contract(address, _abi, runner) as unknown as ODPTestWallet;
    }
  }

  
  