/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IODPRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IODPRegistry__factory>
  getContractFactory(name: 'ODPAuthorAttestation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPAuthorAttestation__factory>
  getContractFactory(name: 'ODPEditionUnits', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPEditionUnits__factory>
  getContractFactory(name: 'ODPHosting', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPHosting__factory>
  getContractFactory(name: 'ODPPassportConcerns', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPPassportConcerns__factory>
  getContractFactory(name: 'ODPPassportProofRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPPassportProofRegistry__factory>
  getContractFactory(name: 'ODPProfileDirectory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPProfileDirectory__factory>
  getContractFactory(name: 'ODPRegistryRelations', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPRegistryRelations__factory>
  getContractFactory(name: 'ODPSatellite', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPSatellite__factory>
  getContractFactory(name: 'ODPStatementJournal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPStatementJournal__factory>
  getContractFactory(name: 'ODPTestWallet', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPTestWallet__factory>
  getContractFactory(name: 'ODPWalletDocumentAnchor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ODPWalletDocumentAnchor__factory>
  getContractFactory(name: 'ObjectDigitalPassport', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ObjectDigitalPassport__factory>

  getContractAt(name: 'IODPRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IODPRegistry>
  getContractAt(name: 'ODPAuthorAttestation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPAuthorAttestation>
  getContractAt(name: 'ODPEditionUnits', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPEditionUnits>
  getContractAt(name: 'ODPHosting', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPHosting>
  getContractAt(name: 'ODPPassportConcerns', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPPassportConcerns>
  getContractAt(name: 'ODPPassportProofRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPPassportProofRegistry>
  getContractAt(name: 'ODPProfileDirectory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPProfileDirectory>
  getContractAt(name: 'ODPRegistryRelations', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPRegistryRelations>
  getContractAt(name: 'ODPSatellite', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPSatellite>
  getContractAt(name: 'ODPStatementJournal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPStatementJournal>
  getContractAt(name: 'ODPTestWallet', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPTestWallet>
  getContractAt(name: 'ODPWalletDocumentAnchor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ODPWalletDocumentAnchor>
  getContractAt(name: 'ObjectDigitalPassport', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ObjectDigitalPassport>

  deployContract(name: 'IODPRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IODPRegistry>
  deployContract(name: 'ODPAuthorAttestation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPAuthorAttestation>
  deployContract(name: 'ODPEditionUnits', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPEditionUnits>
  deployContract(name: 'ODPHosting', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPHosting>
  deployContract(name: 'ODPPassportConcerns', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPPassportConcerns>
  deployContract(name: 'ODPPassportProofRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPPassportProofRegistry>
  deployContract(name: 'ODPProfileDirectory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPProfileDirectory>
  deployContract(name: 'ODPRegistryRelations', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPRegistryRelations>
  deployContract(name: 'ODPSatellite', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPSatellite>
  deployContract(name: 'ODPStatementJournal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPStatementJournal>
  deployContract(name: 'ODPTestWallet', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPTestWallet>
  deployContract(name: 'ODPWalletDocumentAnchor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPWalletDocumentAnchor>
  deployContract(name: 'ObjectDigitalPassport', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ObjectDigitalPassport>

  deployContract(name: 'IODPRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IODPRegistry>
  deployContract(name: 'ODPAuthorAttestation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPAuthorAttestation>
  deployContract(name: 'ODPEditionUnits', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPEditionUnits>
  deployContract(name: 'ODPHosting', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPHosting>
  deployContract(name: 'ODPPassportConcerns', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPPassportConcerns>
  deployContract(name: 'ODPPassportProofRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPPassportProofRegistry>
  deployContract(name: 'ODPProfileDirectory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPProfileDirectory>
  deployContract(name: 'ODPRegistryRelations', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPRegistryRelations>
  deployContract(name: 'ODPSatellite', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPSatellite>
  deployContract(name: 'ODPStatementJournal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPStatementJournal>
  deployContract(name: 'ODPTestWallet', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPTestWallet>
  deployContract(name: 'ODPWalletDocumentAnchor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ODPWalletDocumentAnchor>
  deployContract(name: 'ObjectDigitalPassport', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ObjectDigitalPassport>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
