/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IODPRegistry {
      
    export type CreatorRecordStruct = {creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish}

    export type CreatorRecordStructOutput = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint] & {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint }
  

    export type PassportClassificationViewStruct = {contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish, timestamp: BigNumberish, revoked: boolean, revokedAt: BigNumberish, revocationReasonHash: BytesLike}

    export type PassportClassificationViewStructOutput = [contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string] & {contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string }
  

    export type PassportHeaderViewStruct = {passportId: string, contractVersion: BigNumberish, creator: AddressLike, creatorId: string, year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, objectType: string}

    export type PassportHeaderViewStructOutput = [passportId: string, contractVersion: bigint, creator: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string] & {passportId: string, contractVersion: bigint, creator: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string }
  

    export type PassportMediaViewStruct = {dataHash: BytesLike, imageHash: BytesLike, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, editionCommitment: BytesLike}

    export type PassportMediaViewStructOutput = [dataHash: string, imageHash: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, editionCommitment: string] & {dataHash: string, imageHash: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, editionCommitment: string }
  

    export type PassportReleaseViewStruct = {revocationDeadline: BigNumberish, printFinalizedAt: BigNumberish}

    export type PassportReleaseViewStructOutput = [revocationDeadline: bigint, printFinalizedAt: bigint] & {revocationDeadline: bigint, printFinalizedAt: bigint }
  
    }

  export interface IODPRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getCreator" | "getCreatorByWallet" | "getPassportClassification" | "getPassportHeader" | "getPassportMedia" | "getPassportReleaseState" | "passportExists"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getCreator', values: [string]): string;
encodeFunctionData(functionFragment: 'getCreatorByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPassportClassification', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportHeader', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportMedia', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportReleaseState', values: [string]): string;
encodeFunctionData(functionFragment: 'passportExists', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportClassification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportHeader', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportMedia', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportReleaseState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passportExists', data: BytesLike): Result;
  }

  

  export interface IODPRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IODPRegistry;
    waitForDeployment(): Promise<this>;

    interface: IODPRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCreator: TypedContractMethod<
      [id: string, ],
      [IODPRegistry.CreatorRecordStructOutput],
      'view'
    >
    

    
    getCreatorByWallet: TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >
    

    
    getPassportClassification: TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportClassificationViewStructOutput],
      'view'
    >
    

    
    getPassportHeader: TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportHeaderViewStructOutput],
      'view'
    >
    

    
    getPassportMedia: TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportMediaViewStructOutput],
      'view'
    >
    

    
    getPassportReleaseState: TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportReleaseViewStructOutput],
      'view'
    >
    

    
    passportExists: TypedContractMethod<
      [id: string, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCreator'): TypedContractMethod<
      [id: string, ],
      [IODPRegistry.CreatorRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorByWallet'): TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportClassification'): TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportClassificationViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportHeader'): TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportHeaderViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportMedia'): TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportMediaViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportReleaseState'): TypedContractMethod<
      [id: string, ],
      [IODPRegistry.PassportReleaseViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'passportExists'): TypedContractMethod<
      [id: string, ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }