/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type PassportCoreMintInputsStruct = {year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish}

    export type PassportCoreMintInputsStructOutput = [year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint] & {year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint }
  

    export type PassportMintInputsStruct = {core: PassportCoreMintInputsStruct, dataHash: BytesLike, imageHash: BytesLike, previewHash: BytesLike, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, editionCommitment: BytesLike}

    export type PassportMintInputsStructOutput = [core: PassportCoreMintInputsStructOutput, dataHash: string, imageHash: string, previewHash: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, editionCommitment: string] & {core: PassportCoreMintInputsStructOutput, dataHash: string, imageHash: string, previewHash: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, editionCommitment: string }
  

export declare namespace ObjectDigitalPassport {
      
    export type CreatorRecordStruct = {creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish}

    export type CreatorRecordStructOutput = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint] & {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint }
  

    export type PassportClassificationViewStruct = {contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish, timestamp: BigNumberish, revoked: boolean, revokedAt: BigNumberish, revocationReasonHash: BytesLike}

    export type PassportClassificationViewStructOutput = [contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string] & {contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string }
  

    export type PassportHeaderViewStruct = {passportId: string, contractVersion: BigNumberish, creator: AddressLike, creatorId: string, year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, objectType: string}

    export type PassportHeaderViewStructOutput = [passportId: string, contractVersion: bigint, creator: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string] & {passportId: string, contractVersion: bigint, creator: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string }
  

    export type PassportMediaViewStruct = {dataHash: BytesLike, imageHash: BytesLike, previewHash: BytesLike, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, editionCommitment: BytesLike}

    export type PassportMediaViewStructOutput = [dataHash: string, imageHash: string, previewHash: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, editionCommitment: string] & {dataHash: string, imageHash: string, previewHash: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, editionCommitment: string }
  

    export type PassportReleaseViewStruct = {revocationDeadline: BigNumberish, printFinalizedAt: BigNumberish}

    export type PassportReleaseViewStructOutput = [revocationDeadline: bigint, printFinalizedAt: bigint] & {revocationDeadline: bigint, printFinalizedAt: bigint }
  
    }

  export interface ObjectDigitalPassportInterface extends Interface {
    getFunction(nameOrSignature: "CONTRACT_VERSION" | "ISSUER_REVOCATION_WINDOW" | "MAX_PAGE_SIZE" | "PERSONAL_REVOCATION_WINDOW" | "finalizePassportForPrint" | "getCreator" | "getCreatorByWallet" | "getMintOperation" | "getPassportClassification" | "getPassportHeader" | "getPassportMedia" | "getPassportReleaseState" | "getPassportsByCreatorPaged" | "mintDigital" | "mintMixed" | "mintPhysical" | "passportExists" | "registerCreator" | "revokePassport"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CreatorRegistered" | "MintOperationCommitted" | "PassportFinalizedForPrint" | "PassportMinted" | "PassportRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'CONTRACT_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'ISSUER_REVOCATION_WINDOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PAGE_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PERSONAL_REVOCATION_WINDOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizePassportForPrint', values: [string]): string;
encodeFunctionData(functionFragment: 'getCreator', values: [string]): string;
encodeFunctionData(functionFragment: 'getCreatorByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMintOperation', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getPassportClassification', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportHeader', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportMedia', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportReleaseState', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportsByCreatorPaged', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintDigital', values: [PassportMintInputsStruct, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintMixed', values: [PassportMintInputsStruct, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintPhysical', values: [PassportMintInputsStruct, BytesLike]): string;
encodeFunctionData(functionFragment: 'passportExists', values: [string]): string;
encodeFunctionData(functionFragment: 'registerCreator', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'revokePassport', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'CONTRACT_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ISSUER_REVOCATION_WINDOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PAGE_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PERSONAL_REVOCATION_WINDOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizePassportForPrint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMintOperation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportClassification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportHeader', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportMedia', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportReleaseState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportsByCreatorPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintDigital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintMixed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPhysical', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passportExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokePassport', data: BytesLike): Result;
  }

  
    export namespace CreatorRegisteredEvent {
      export type InputTuple = [creatorId: string, creatorIdText: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [creatorId: string, creatorIdText: string, wallet: string, typePrefix: string, timestamp: bigint];
      export interface OutputObject {creatorId: string, creatorIdText: string, wallet: string, typePrefix: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintOperationCommittedEvent {
      export type InputTuple = [issuer: AddressLike, operationId: BytesLike, digest: BytesLike, passportId: string];
      export type OutputTuple = [issuer: string, operationId: string, digest: string, passportId: string];
      export interface OutputObject {issuer: string, operationId: string, digest: string, passportId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportFinalizedForPrintEvent {
      export type InputTuple = [passportId: string, passportIdText: string, issuer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, passportIdText: string, issuer: string, timestamp: bigint];
      export interface OutputObject {passportId: string, passportIdText: string, issuer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportMintedEvent {
      export type InputTuple = [passportId: string, passportIdText: string, creator: AddressLike, creatorId: string, title: string, authorName: string, domain: string, objectType: string, contentClass: BigNumberish, year: BigNumberish, month: BigNumberish, dataHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, timestamp: BigNumberish, operationId: BytesLike];
      export type OutputTuple = [passportId: string, passportIdText: string, creator: string, creatorId: string, title: string, authorName: string, domain: string, objectType: string, contentClass: bigint, year: bigint, month: bigint, dataHash: string, anchorsHash: string, anchorTypesMask: bigint, timestamp: bigint, operationId: string];
      export interface OutputObject {passportId: string, passportIdText: string, creator: string, creatorId: string, title: string, authorName: string, domain: string, objectType: string, contentClass: bigint, year: bigint, month: bigint, dataHash: string, anchorsHash: string, anchorTypesMask: bigint, timestamp: bigint, operationId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportRevokedEvent {
      export type InputTuple = [passportId: string, passportIdText: string, revokedBy: AddressLike, reasonHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, passportIdText: string, revokedBy: string, reasonHash: string, timestamp: bigint];
      export interface OutputObject {passportId: string, passportIdText: string, revokedBy: string, reasonHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ObjectDigitalPassport extends BaseContract {
    
    connect(runner?: ContractRunner | null): ObjectDigitalPassport;
    waitForDeployment(): Promise<this>;

    interface: ObjectDigitalPassportInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CONTRACT_VERSION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ISSUER_REVOCATION_WINDOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PAGE_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PERSONAL_REVOCATION_WINDOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalizePassportForPrint: TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >
    

    
    getCreator: TypedContractMethod<
      [creatorId: string, ],
      [ObjectDigitalPassport.CreatorRecordStructOutput],
      'view'
    >
    

    
    getCreatorByWallet: TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >
    

    
    getMintOperation: TypedContractMethod<
      [issuer: AddressLike, operationId: BytesLike, ],
      [[string, string] & {digest: string, passportId: string }],
      'view'
    >
    

    
    getPassportClassification: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportClassificationViewStructOutput],
      'view'
    >
    

    
    getPassportHeader: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportHeaderViewStructOutput],
      'view'
    >
    

    
    getPassportMedia: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportMediaViewStructOutput],
      'view'
    >
    

    
    getPassportReleaseState: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportReleaseViewStructOutput],
      'view'
    >
    

    
    getPassportsByCreatorPaged: TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {result: string[], total: bigint }],
      'view'
    >
    

    
    mintDigital: TypedContractMethod<
      [m: PassportMintInputsStruct, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    mintMixed: TypedContractMethod<
      [m: PassportMintInputsStruct, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    mintPhysical: TypedContractMethod<
      [m: PassportMintInputsStruct, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    passportExists: TypedContractMethod<
      [id: string, ],
      [boolean],
      'view'
    >
    

    
    registerCreator: TypedContractMethod<
      [typePrefix: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    revokePassport: TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CONTRACT_VERSION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ISSUER_REVOCATION_WINDOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PAGE_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PERSONAL_REVOCATION_WINDOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalizePassportForPrint'): TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCreator'): TypedContractMethod<
      [creatorId: string, ],
      [ObjectDigitalPassport.CreatorRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorByWallet'): TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMintOperation'): TypedContractMethod<
      [issuer: AddressLike, operationId: BytesLike, ],
      [[string, string] & {digest: string, passportId: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportClassification'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportClassificationViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportHeader'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportHeaderViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportMedia'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportMediaViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportReleaseState'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportReleaseViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportsByCreatorPaged'): TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {result: string[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'mintDigital'): TypedContractMethod<
      [m: PassportMintInputsStruct, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintMixed'): TypedContractMethod<
      [m: PassportMintInputsStruct, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintPhysical'): TypedContractMethod<
      [m: PassportMintInputsStruct, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'passportExists'): TypedContractMethod<
      [id: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerCreator'): TypedContractMethod<
      [typePrefix: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokePassport'): TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CreatorRegistered'): TypedContractEvent<CreatorRegisteredEvent.InputTuple, CreatorRegisteredEvent.OutputTuple, CreatorRegisteredEvent.OutputObject>;
getEvent(key: 'MintOperationCommitted'): TypedContractEvent<MintOperationCommittedEvent.InputTuple, MintOperationCommittedEvent.OutputTuple, MintOperationCommittedEvent.OutputObject>;
getEvent(key: 'PassportFinalizedForPrint'): TypedContractEvent<PassportFinalizedForPrintEvent.InputTuple, PassportFinalizedForPrintEvent.OutputTuple, PassportFinalizedForPrintEvent.OutputObject>;
getEvent(key: 'PassportMinted'): TypedContractEvent<PassportMintedEvent.InputTuple, PassportMintedEvent.OutputTuple, PassportMintedEvent.OutputObject>;
getEvent(key: 'PassportRevoked'): TypedContractEvent<PassportRevokedEvent.InputTuple, PassportRevokedEvent.OutputTuple, PassportRevokedEvent.OutputObject>;

    filters: {
      
      'CreatorRegistered(string,string,address,bytes1,uint256)': TypedContractEvent<CreatorRegisteredEvent.InputTuple, CreatorRegisteredEvent.OutputTuple, CreatorRegisteredEvent.OutputObject>;
      CreatorRegistered: TypedContractEvent<CreatorRegisteredEvent.InputTuple, CreatorRegisteredEvent.OutputTuple, CreatorRegisteredEvent.OutputObject>;
    

      'MintOperationCommitted(address,bytes32,bytes32,string)': TypedContractEvent<MintOperationCommittedEvent.InputTuple, MintOperationCommittedEvent.OutputTuple, MintOperationCommittedEvent.OutputObject>;
      MintOperationCommitted: TypedContractEvent<MintOperationCommittedEvent.InputTuple, MintOperationCommittedEvent.OutputTuple, MintOperationCommittedEvent.OutputObject>;
    

      'PassportFinalizedForPrint(string,string,address,uint256)': TypedContractEvent<PassportFinalizedForPrintEvent.InputTuple, PassportFinalizedForPrintEvent.OutputTuple, PassportFinalizedForPrintEvent.OutputObject>;
      PassportFinalizedForPrint: TypedContractEvent<PassportFinalizedForPrintEvent.InputTuple, PassportFinalizedForPrintEvent.OutputTuple, PassportFinalizedForPrintEvent.OutputObject>;
    

      'PassportMinted(string,string,address,string,string,string,string,string,uint8,uint32,uint8,bytes32,bytes32,uint32,uint256,bytes32)': TypedContractEvent<PassportMintedEvent.InputTuple, PassportMintedEvent.OutputTuple, PassportMintedEvent.OutputObject>;
      PassportMinted: TypedContractEvent<PassportMintedEvent.InputTuple, PassportMintedEvent.OutputTuple, PassportMintedEvent.OutputObject>;
    

      'PassportRevoked(string,string,address,bytes32,uint256)': TypedContractEvent<PassportRevokedEvent.InputTuple, PassportRevokedEvent.OutputTuple, PassportRevokedEvent.OutputObject>;
      PassportRevoked: TypedContractEvent<PassportRevokedEvent.InputTuple, PassportRevokedEvent.OutputTuple, PassportRevokedEvent.OutputObject>;
    
    };
  }