/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ODPAuthorAttestationInterface extends Interface {
    getFunction(nameOrSignature: "attestAuthor" | "authorWithdrawalAt" | "authorWithdrawalReason" | "domainSeparator" | "getAuthorAttestation" | "hashAuthorAttestation" | "odpRegistry" | "withdrawAuthorAttestation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorAttestationWithdrawn" | "AuthorAttested"): EventFragment;

    encodeFunctionData(functionFragment: 'attestAuthor', values: [string, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'authorWithdrawalAt', values: [string]): string;
encodeFunctionData(functionFragment: 'authorWithdrawalReason', values: [string]): string;
encodeFunctionData(functionFragment: 'domainSeparator', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuthorAttestation', values: [string]): string;
encodeFunctionData(functionFragment: 'hashAuthorAttestation', values: [string, BytesLike, string, AddressLike]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawAuthorAttestation', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'attestAuthor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorWithdrawalAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorWithdrawalReason', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'domainSeparator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuthorAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hashAuthorAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawAuthorAttestation', data: BytesLike): Result;
  }

  
    export namespace AuthorAttestationWithdrawnEvent {
      export type InputTuple = [passportId: string, passportIdText: string, authorSigner: AddressLike, reasonHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, passportIdText: string, authorSigner: string, reasonHash: string, timestamp: bigint];
      export interface OutputObject {passportId: string, passportIdText: string, authorSigner: string, reasonHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuthorAttestedEvent {
      export type InputTuple = [passportId: string, passportIdText: string, creatorIdText: string, authorSigner: AddressLike, creatorId: string, dataHash: BytesLike, submittedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, passportIdText: string, creatorIdText: string, authorSigner: string, creatorId: string, dataHash: string, submittedBy: string, timestamp: bigint];
      export interface OutputObject {passportId: string, passportIdText: string, creatorIdText: string, authorSigner: string, creatorId: string, dataHash: string, submittedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPAuthorAttestation extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPAuthorAttestation;
    waitForDeployment(): Promise<this>;

    interface: ODPAuthorAttestationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attestAuthor: TypedContractMethod<
      [passportId: string, authorSigner: AddressLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorWithdrawalAt: TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >
    

    
    authorWithdrawalReason: TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >
    

    
    domainSeparator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAuthorAttestation: TypedContractMethod<
      [passportId: string, ],
      [[boolean, string, string, string, bigint] & {attested: boolean, authorSigner: string, dataHash: string, creatorId: string, timestamp: bigint }],
      'view'
    >
    

    
    hashAuthorAttestation: TypedContractMethod<
      [passportId: string, dataHash: BytesLike, creatorId: string, authorSigner: AddressLike, ],
      [string],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawAuthorAttestation: TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attestAuthor'): TypedContractMethod<
      [passportId: string, authorSigner: AddressLike, signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorWithdrawalAt'): TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorWithdrawalReason'): TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'domainSeparator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAuthorAttestation'): TypedContractMethod<
      [passportId: string, ],
      [[boolean, string, string, string, bigint] & {attested: boolean, authorSigner: string, dataHash: string, creatorId: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hashAuthorAttestation'): TypedContractMethod<
      [passportId: string, dataHash: BytesLike, creatorId: string, authorSigner: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawAuthorAttestation'): TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuthorAttestationWithdrawn'): TypedContractEvent<AuthorAttestationWithdrawnEvent.InputTuple, AuthorAttestationWithdrawnEvent.OutputTuple, AuthorAttestationWithdrawnEvent.OutputObject>;
getEvent(key: 'AuthorAttested'): TypedContractEvent<AuthorAttestedEvent.InputTuple, AuthorAttestedEvent.OutputTuple, AuthorAttestedEvent.OutputObject>;

    filters: {
      
      'AuthorAttestationWithdrawn(string,string,address,bytes32,uint256)': TypedContractEvent<AuthorAttestationWithdrawnEvent.InputTuple, AuthorAttestationWithdrawnEvent.OutputTuple, AuthorAttestationWithdrawnEvent.OutputObject>;
      AuthorAttestationWithdrawn: TypedContractEvent<AuthorAttestationWithdrawnEvent.InputTuple, AuthorAttestationWithdrawnEvent.OutputTuple, AuthorAttestationWithdrawnEvent.OutputObject>;
    

      'AuthorAttested(string,string,string,address,string,bytes32,address,uint256)': TypedContractEvent<AuthorAttestedEvent.InputTuple, AuthorAttestedEvent.OutputTuple, AuthorAttestedEvent.OutputObject>;
      AuthorAttested: TypedContractEvent<AuthorAttestedEvent.InputTuple, AuthorAttestedEvent.OutputTuple, AuthorAttestedEvent.OutputObject>;
    
    };
  }