/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ODPEditionUnitsInterface extends Interface {
    getFunction(nameOrSignature: "activate" | "activationPayloadHash" | "commitmentFor" | "editionPassportByNonce" | "getActivation" | "getEdition" | "isActivated" | "labelPayloadHash" | "odpRegistry" | "openEdition" | "unitLeaf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EditionOpened" | "UnitActivated"): EventFragment;

    encodeFunctionData(functionFragment: 'activate', values: [string, BigNumberish, BytesLike[], BytesLike]): string;
encodeFunctionData(functionFragment: 'activationPayloadHash', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'commitmentFor', values: [AddressLike, BytesLike, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'editionPassportByNonce', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getActivation', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEdition', values: [string]): string;
encodeFunctionData(functionFragment: 'isActivated', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'labelPayloadHash', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'openEdition', values: [string, BytesLike, BigNumberish, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'unitLeaf', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'activate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activationPayloadHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitmentFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'editionPassportByNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActivation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEdition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActivated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'labelPayloadHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openEdition', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unitLeaf', data: BytesLike): Result;
  }

  
    export namespace EditionOpenedEvent {
      export type InputTuple = [editionPassportId: string, merkleRoot: BytesLike, unitCount: BigNumberish, labelSigner: AddressLike, editionNonce: BytesLike, issuer: AddressLike];
      export type OutputTuple = [editionPassportId: string, merkleRoot: string, unitCount: bigint, labelSigner: string, editionNonce: string, issuer: string];
      export interface OutputObject {editionPassportId: string, merkleRoot: string, unitCount: bigint, labelSigner: string, editionNonce: string, issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnitActivatedEvent {
      export type InputTuple = [editionPassportId: string, unitIndex: BigNumberish, unitAddress: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [editionPassportId: string, unitIndex: bigint, unitAddress: string, timestamp: bigint];
      export interface OutputObject {editionPassportId: string, unitIndex: bigint, unitAddress: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPEditionUnits extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPEditionUnits;
    waitForDeployment(): Promise<this>;

    interface: ODPEditionUnitsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activate: TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, proof: BytesLike[], signature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    activationPayloadHash: TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [string],
      'view'
    >
    

    
    commitmentFor: TypedContractMethod<
      [issuer: AddressLike, root: BytesLike, count: BigNumberish, labelSigner: AddressLike, nonce: BytesLike, ],
      [string],
      'view'
    >
    

    
    editionPassportByNonce: TypedContractMethod<
      [issuer: AddressLike, nonce: BytesLike, ],
      [string],
      'view'
    >
    

    
    getActivation: TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [[bigint, string] & {timestamp: bigint, unitAddress: string }],
      'view'
    >
    

    
    getEdition: TypedContractMethod<
      [editionPassportId: string, ],
      [[string, bigint, boolean, string, string] & {merkleRoot: string, unitCount: bigint, open: boolean, editionNonce: string, labelSigner: string }],
      'view'
    >
    

    
    isActivated: TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    labelPayloadHash: TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [string],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    openEdition: TypedContractMethod<
      [editionPassportId: string, merkleRoot: BytesLike, unitCount: BigNumberish, labelSigner: AddressLike, editionNonce: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    unitLeaf: TypedContractMethod<
      [unitIndex: BigNumberish, unitAddress: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activate'): TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, proof: BytesLike[], signature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'activationPayloadHash'): TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'commitmentFor'): TypedContractMethod<
      [issuer: AddressLike, root: BytesLike, count: BigNumberish, labelSigner: AddressLike, nonce: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'editionPassportByNonce'): TypedContractMethod<
      [issuer: AddressLike, nonce: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getActivation'): TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [[bigint, string] & {timestamp: bigint, unitAddress: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getEdition'): TypedContractMethod<
      [editionPassportId: string, ],
      [[string, bigint, boolean, string, string] & {merkleRoot: string, unitCount: bigint, open: boolean, editionNonce: string, labelSigner: string }],
      'view'
    >;
getFunction(nameOrSignature: 'isActivated'): TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'labelPayloadHash'): TypedContractMethod<
      [editionPassportId: string, unitIndex: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'openEdition'): TypedContractMethod<
      [editionPassportId: string, merkleRoot: BytesLike, unitCount: BigNumberish, labelSigner: AddressLike, editionNonce: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unitLeaf'): TypedContractMethod<
      [unitIndex: BigNumberish, unitAddress: AddressLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'EditionOpened'): TypedContractEvent<EditionOpenedEvent.InputTuple, EditionOpenedEvent.OutputTuple, EditionOpenedEvent.OutputObject>;
getEvent(key: 'UnitActivated'): TypedContractEvent<UnitActivatedEvent.InputTuple, UnitActivatedEvent.OutputTuple, UnitActivatedEvent.OutputObject>;

    filters: {
      
      'EditionOpened(string,bytes32,uint32,address,bytes32,address)': TypedContractEvent<EditionOpenedEvent.InputTuple, EditionOpenedEvent.OutputTuple, EditionOpenedEvent.OutputObject>;
      EditionOpened: TypedContractEvent<EditionOpenedEvent.InputTuple, EditionOpenedEvent.OutputTuple, EditionOpenedEvent.OutputObject>;
    

      'UnitActivated(string,uint32,address,uint256)': TypedContractEvent<UnitActivatedEvent.InputTuple, UnitActivatedEvent.OutputTuple, UnitActivatedEvent.OutputObject>;
      UnitActivated: TypedContractEvent<UnitActivatedEvent.InputTuple, UnitActivatedEvent.OutputTuple, UnitActivatedEvent.OutputObject>;
    
    };
  }