/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ODPHosting {
      
    export type LocationsStruct = {dataUrl: string, imageUrl: string, updatedAt: BigNumberish}

    export type LocationsStructOutput = [dataUrl: string, imageUrl: string, updatedAt: bigint] & {dataUrl: string, imageUrl: string, updatedAt: bigint }
  

    export type DelegationStruct = {agent: AddressLike, expiresAt: BigNumberish}

    export type DelegationStructOutput = [agent: string, expiresAt: bigint] & {agent: string, expiresAt: bigint }
  
    }

  export interface ODPHostingInterface extends Interface {
    getFunction(nameOrSignature: "delegatePublishing" | "getLocations" | "getPublishingDelegation" | "odpRegistry" | "revokePublishing" | "updateLocations"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LocationsUpdated" | "PublishingDelegated"): EventFragment;

    encodeFunctionData(functionFragment: 'delegatePublishing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLocations', values: [string]): string;
encodeFunctionData(functionFragment: 'getPublishingDelegation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokePublishing', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateLocations', values: [string, string, string]): string;

    decodeFunctionResult(functionFragment: 'delegatePublishing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLocations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublishingDelegation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokePublishing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateLocations', data: BytesLike): Result;
  }

  
    export namespace LocationsUpdatedEvent {
      export type InputTuple = [passportId: string, passportIdText: string, dataUrl: string, imageUrl: string, updatedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, passportIdText: string, dataUrl: string, imageUrl: string, updatedBy: string, timestamp: bigint];
      export interface OutputObject {passportId: string, passportIdText: string, dataUrl: string, imageUrl: string, updatedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PublishingDelegatedEvent {
      export type InputTuple = [creator: AddressLike, agent: AddressLike, expiresAt: BigNumberish];
      export type OutputTuple = [creator: string, agent: string, expiresAt: bigint];
      export interface OutputObject {creator: string, agent: string, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPHosting extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPHosting;
    waitForDeployment(): Promise<this>;

    interface: ODPHostingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    delegatePublishing: TypedContractMethod<
      [agent: AddressLike, expiresAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getLocations: TypedContractMethod<
      [id: string, ],
      [ODPHosting.LocationsStructOutput],
      'view'
    >
    

    
    getPublishingDelegation: TypedContractMethod<
      [creator: AddressLike, ],
      [ODPHosting.DelegationStructOutput],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokePublishing: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateLocations: TypedContractMethod<
      [id: string, dataUrl: string, imageUrl: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'delegatePublishing'): TypedContractMethod<
      [agent: AddressLike, expiresAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getLocations'): TypedContractMethod<
      [id: string, ],
      [ODPHosting.LocationsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPublishingDelegation'): TypedContractMethod<
      [creator: AddressLike, ],
      [ODPHosting.DelegationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokePublishing'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateLocations'): TypedContractMethod<
      [id: string, dataUrl: string, imageUrl: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'LocationsUpdated'): TypedContractEvent<LocationsUpdatedEvent.InputTuple, LocationsUpdatedEvent.OutputTuple, LocationsUpdatedEvent.OutputObject>;
getEvent(key: 'PublishingDelegated'): TypedContractEvent<PublishingDelegatedEvent.InputTuple, PublishingDelegatedEvent.OutputTuple, PublishingDelegatedEvent.OutputObject>;

    filters: {
      
      'LocationsUpdated(string,string,string,string,address,uint256)': TypedContractEvent<LocationsUpdatedEvent.InputTuple, LocationsUpdatedEvent.OutputTuple, LocationsUpdatedEvent.OutputObject>;
      LocationsUpdated: TypedContractEvent<LocationsUpdatedEvent.InputTuple, LocationsUpdatedEvent.OutputTuple, LocationsUpdatedEvent.OutputObject>;
    

      'PublishingDelegated(address,address,uint256)': TypedContractEvent<PublishingDelegatedEvent.InputTuple, PublishingDelegatedEvent.OutputTuple, PublishingDelegatedEvent.OutputObject>;
      PublishingDelegated: TypedContractEvent<PublishingDelegatedEvent.InputTuple, PublishingDelegatedEvent.OutputTuple, PublishingDelegatedEvent.OutputObject>;
    
    };
  }