/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ODPProfileDirectoryInterface extends Interface {
    getFunction(nameOrSignature: "getDomain" | "odpRegistry" | "setDomain"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DomainUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'getDomain', values: [string]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'setDomain', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getDomain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDomain', data: BytesLike): Result;
  }

  
    export namespace DomainUpdatedEvent {
      export type InputTuple = [creatorId: string, creatorIdText: string, domain: string, timestamp: BigNumberish];
      export type OutputTuple = [creatorId: string, creatorIdText: string, domain: string, timestamp: bigint];
      export interface OutputObject {creatorId: string, creatorIdText: string, domain: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPProfileDirectory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPProfileDirectory;
    waitForDeployment(): Promise<this>;

    interface: ODPProfileDirectoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getDomain: TypedContractMethod<
      [id: string, ],
      [string],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setDomain: TypedContractMethod<
      [domain: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getDomain'): TypedContractMethod<
      [id: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setDomain'): TypedContractMethod<
      [domain: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DomainUpdated'): TypedContractEvent<DomainUpdatedEvent.InputTuple, DomainUpdatedEvent.OutputTuple, DomainUpdatedEvent.OutputObject>;

    filters: {
      
      'DomainUpdated(string,string,string,uint256)': TypedContractEvent<DomainUpdatedEvent.InputTuple, DomainUpdatedEvent.OutputTuple, DomainUpdatedEvent.OutputObject>;
      DomainUpdated: TypedContractEvent<DomainUpdatedEvent.InputTuple, DomainUpdatedEvent.OutputTuple, DomainUpdatedEvent.OutputObject>;
    
    };
  }