/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ODPPassportProofRegistry {
      
    export type ProofRecordStruct = {proofId: string, contractVersion: BigNumberish, prover: string, passportId: string, documentHash: BytesLike, documentUrl: string, timestamp: BigNumberish}

    export type ProofRecordStructOutput = [proofId: string, contractVersion: bigint, prover: string, passportId: string, documentHash: string, documentUrl: string, timestamp: bigint] & {proofId: string, contractVersion: bigint, prover: string, passportId: string, documentHash: string, documentUrl: string, timestamp: bigint }
  
    }

  export interface ODPPassportProofRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getProof" | "getProofsByInstitutionPaged" | "getProofsForPassportPaged" | "odpRegistry" | "proofAuthor" | "proofOperations" | "proofWithdrawalReason" | "proofWithdrawnAt" | "submitProof" | "withdrawProof"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ProofOperationCommitted" | "ProofSubmitted" | "ProofWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'getProof', values: [string]): string;
encodeFunctionData(functionFragment: 'getProofsByInstitutionPaged', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProofsForPassportPaged', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'proofAuthor', values: [string]): string;
encodeFunctionData(functionFragment: 'proofOperations', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'proofWithdrawalReason', values: [string]): string;
encodeFunctionData(functionFragment: 'proofWithdrawnAt', values: [string]): string;
encodeFunctionData(functionFragment: 'submitProof', values: [string, BytesLike, string, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'withdrawProof', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProofsByInstitutionPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProofsForPassportPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofAuthor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofOperations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofWithdrawalReason', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofWithdrawnAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawProof', data: BytesLike): Result;
  }

  
    export namespace ProofOperationCommittedEvent {
      export type InputTuple = [author: AddressLike, operationId: BytesLike, proofId: string, digest: BytesLike];
      export type OutputTuple = [author: string, operationId: string, proofId: string, digest: string];
      export interface OutputObject {author: string, operationId: string, proofId: string, digest: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofSubmittedEvent {
      export type InputTuple = [proofId: string, passportId: string, prover: string, proofIdText: string, passportIdText: string, proverText: string, timestamp: BigNumberish];
      export type OutputTuple = [proofId: string, passportId: string, prover: string, proofIdText: string, passportIdText: string, proverText: string, timestamp: bigint];
      export interface OutputObject {proofId: string, passportId: string, prover: string, proofIdText: string, passportIdText: string, proverText: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofWithdrawnEvent {
      export type InputTuple = [proofId: string, proofIdText: string, author: AddressLike, reasonHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [proofId: string, proofIdText: string, author: string, reasonHash: string, timestamp: bigint];
      export interface OutputObject {proofId: string, proofIdText: string, author: string, reasonHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPPassportProofRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPPassportProofRegistry;
    waitForDeployment(): Promise<this>;

    interface: ODPPassportProofRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getProof: TypedContractMethod<
      [proofId: string, ],
      [ODPPassportProofRegistry.ProofRecordStructOutput],
      'view'
    >
    

    
    getProofsByInstitutionPaged: TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >
    

    
    getProofsForPassportPaged: TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proofAuthor: TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >
    

    
    proofOperations: TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [[string, string] & {digest: string, proofId: string }],
      'view'
    >
    

    
    proofWithdrawalReason: TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >
    

    
    proofWithdrawnAt: TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >
    

    
    submitProof: TypedContractMethod<
      [passportId: string, documentHash: BytesLike, documentUrl: string, year: BigNumberish, month: BigNumberish, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    withdrawProof: TypedContractMethod<
      [proofId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getProof'): TypedContractMethod<
      [proofId: string, ],
      [ODPPassportProofRegistry.ProofRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProofsByInstitutionPaged'): TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getProofsForPassportPaged'): TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofAuthor'): TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofOperations'): TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [[string, string] & {digest: string, proofId: string }],
      'view'
    >;
getFunction(nameOrSignature: 'proofWithdrawalReason'): TypedContractMethod<
      [arg0: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofWithdrawnAt'): TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitProof'): TypedContractMethod<
      [passportId: string, documentHash: BytesLike, documentUrl: string, year: BigNumberish, month: BigNumberish, operationId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawProof'): TypedContractMethod<
      [proofId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ProofOperationCommitted'): TypedContractEvent<ProofOperationCommittedEvent.InputTuple, ProofOperationCommittedEvent.OutputTuple, ProofOperationCommittedEvent.OutputObject>;
getEvent(key: 'ProofSubmitted'): TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
getEvent(key: 'ProofWithdrawn'): TypedContractEvent<ProofWithdrawnEvent.InputTuple, ProofWithdrawnEvent.OutputTuple, ProofWithdrawnEvent.OutputObject>;

    filters: {
      
      'ProofOperationCommitted(address,bytes32,string,bytes32)': TypedContractEvent<ProofOperationCommittedEvent.InputTuple, ProofOperationCommittedEvent.OutputTuple, ProofOperationCommittedEvent.OutputObject>;
      ProofOperationCommitted: TypedContractEvent<ProofOperationCommittedEvent.InputTuple, ProofOperationCommittedEvent.OutputTuple, ProofOperationCommittedEvent.OutputObject>;
    

      'ProofSubmitted(string,string,string,string,string,string,uint256)': TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
      ProofSubmitted: TypedContractEvent<ProofSubmittedEvent.InputTuple, ProofSubmittedEvent.OutputTuple, ProofSubmittedEvent.OutputObject>;
    

      'ProofWithdrawn(string,string,address,bytes32,uint256)': TypedContractEvent<ProofWithdrawnEvent.InputTuple, ProofWithdrawnEvent.OutputTuple, ProofWithdrawnEvent.OutputObject>;
      ProofWithdrawn: TypedContractEvent<ProofWithdrawnEvent.InputTuple, ProofWithdrawnEvent.OutputTuple, ProofWithdrawnEvent.OutputObject>;
    
    };
  }