/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ODPPassportConcerns {
      
    export type ConcernStruct = {raisedBy: string, reasonHash: BytesLike, reasonUrl: string, raisedAt: BigNumberish, withdrawnAt: BigNumberish}

    export type ConcernStructOutput = [raisedBy: string, reasonHash: string, reasonUrl: string, raisedAt: bigint, withdrawnAt: bigint] & {raisedBy: string, reasonHash: string, reasonUrl: string, raisedAt: bigint, withdrawnAt: bigint }
  
    }

  export interface ODPPassportConcernsInterface extends Interface {
    getFunction(nameOrSignature: "activeConcernCount" | "getConcern" | "getConcernRaisersPaged" | "getConcernsByRaiserPaged" | "odpRegistry" | "raiseConcern" | "withdrawConcern"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConcernRaised" | "ConcernWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'activeConcernCount', values: [string]): string;
encodeFunctionData(functionFragment: 'getConcern', values: [string, string]): string;
encodeFunctionData(functionFragment: 'getConcernRaisersPaged', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getConcernsByRaiserPaged', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseConcern', values: [string, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'withdrawConcern', values: [string]): string;

    decodeFunctionResult(functionFragment: 'activeConcernCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConcern', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConcernRaisersPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConcernsByRaiserPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseConcern', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawConcern', data: BytesLike): Result;
  }

  
    export namespace ConcernRaisedEvent {
      export type InputTuple = [passportId: string, raisedBy: string, passportIdText: string, raisedByText: string, reasonHash: BytesLike, reasonUrl: string, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, raisedBy: string, passportIdText: string, raisedByText: string, reasonHash: string, reasonUrl: string, timestamp: bigint];
      export interface OutputObject {passportId: string, raisedBy: string, passportIdText: string, raisedByText: string, reasonHash: string, reasonUrl: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConcernWithdrawnEvent {
      export type InputTuple = [passportId: string, raisedBy: string, passportIdText: string, raisedByText: string, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, raisedBy: string, passportIdText: string, raisedByText: string, timestamp: bigint];
      export interface OutputObject {passportId: string, raisedBy: string, passportIdText: string, raisedByText: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPPassportConcerns extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPPassportConcerns;
    waitForDeployment(): Promise<this>;

    interface: ODPPassportConcernsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeConcernCount: TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >
    

    
    getConcern: TypedContractMethod<
      [passportId: string, raisedBy: string, ],
      [ODPPassportConcerns.ConcernStructOutput],
      'view'
    >
    

    
    getConcernRaisersPaged: TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >
    

    
    getConcernsByRaiserPaged: TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    raiseConcern: TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, reasonUrl: string, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawConcern: TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeConcernCount'): TypedContractMethod<
      [arg0: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getConcern'): TypedContractMethod<
      [passportId: string, raisedBy: string, ],
      [ODPPassportConcerns.ConcernStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getConcernRaisersPaged'): TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getConcernsByRaiserPaged'): TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'raiseConcern'): TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, reasonUrl: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawConcern'): TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ConcernRaised'): TypedContractEvent<ConcernRaisedEvent.InputTuple, ConcernRaisedEvent.OutputTuple, ConcernRaisedEvent.OutputObject>;
getEvent(key: 'ConcernWithdrawn'): TypedContractEvent<ConcernWithdrawnEvent.InputTuple, ConcernWithdrawnEvent.OutputTuple, ConcernWithdrawnEvent.OutputObject>;

    filters: {
      
      'ConcernRaised(string,string,string,string,bytes32,string,uint256)': TypedContractEvent<ConcernRaisedEvent.InputTuple, ConcernRaisedEvent.OutputTuple, ConcernRaisedEvent.OutputObject>;
      ConcernRaised: TypedContractEvent<ConcernRaisedEvent.InputTuple, ConcernRaisedEvent.OutputTuple, ConcernRaisedEvent.OutputObject>;
    

      'ConcernWithdrawn(string,string,string,string,uint256)': TypedContractEvent<ConcernWithdrawnEvent.InputTuple, ConcernWithdrawnEvent.OutputTuple, ConcernWithdrawnEvent.OutputObject>;
      ConcernWithdrawn: TypedContractEvent<ConcernWithdrawnEvent.InputTuple, ConcernWithdrawnEvent.OutputTuple, ConcernWithdrawnEvent.OutputObject>;
    
    };
  }