/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ODPRegistryRelationsInterface extends Interface {
    getFunction(nameOrSignature: "cancelAffiliationRequest" | "confirmAffiliation" | "detachAffiliation" | "getAffiliatedChildren" | "getAffiliatedChildrenPaged" | "getAffiliatedParent" | "getAffiliationAudit" | "isAffiliationPending" | "leaveAffiliation" | "odpRegistry" | "proposeAffiliation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AffiliationConfirmed" | "AffiliationDetached" | "AffiliationProposed"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelAffiliationRequest', values: [string]): string;
encodeFunctionData(functionFragment: 'confirmAffiliation', values: [string]): string;
encodeFunctionData(functionFragment: 'detachAffiliation', values: [string]): string;
encodeFunctionData(functionFragment: 'getAffiliatedChildren', values: [string]): string;
encodeFunctionData(functionFragment: 'getAffiliatedChildrenPaged', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAffiliatedParent', values: [string]): string;
encodeFunctionData(functionFragment: 'getAffiliationAudit', values: [string]): string;
encodeFunctionData(functionFragment: 'isAffiliationPending', values: [string, string]): string;
encodeFunctionData(functionFragment: 'leaveAffiliation', values?: undefined): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposeAffiliation', values: [string]): string;

    decodeFunctionResult(functionFragment: 'cancelAffiliationRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmAffiliation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'detachAffiliation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAffiliatedChildren', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAffiliatedChildrenPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAffiliatedParent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAffiliationAudit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAffiliationPending', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leaveAffiliation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeAffiliation', data: BytesLike): Result;
  }

  
    export namespace AffiliationConfirmedEvent {
      export type InputTuple = [parentId: string, childId: string, timestamp: BigNumberish];
      export type OutputTuple = [parentId: string, childId: string, timestamp: bigint];
      export interface OutputObject {parentId: string, childId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AffiliationDetachedEvent {
      export type InputTuple = [parentId: string, childId: string, timestamp: BigNumberish];
      export type OutputTuple = [parentId: string, childId: string, timestamp: bigint];
      export interface OutputObject {parentId: string, childId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AffiliationProposedEvent {
      export type InputTuple = [parentId: string, childId: string, timestamp: BigNumberish];
      export type OutputTuple = [parentId: string, childId: string, timestamp: bigint];
      export interface OutputObject {parentId: string, childId: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPRegistryRelations extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPRegistryRelations;
    waitForDeployment(): Promise<this>;

    interface: ODPRegistryRelationsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelAffiliationRequest: TypedContractMethod<
      [parentId: string, ],
      [void],
      'nonpayable'
    >
    

    
    confirmAffiliation: TypedContractMethod<
      [childId: string, ],
      [void],
      'nonpayable'
    >
    

    
    detachAffiliation: TypedContractMethod<
      [childId: string, ],
      [void],
      'nonpayable'
    >
    

    
    getAffiliatedChildren: TypedContractMethod<
      [parentId: string, ],
      [string[]],
      'view'
    >
    

    
    getAffiliatedChildrenPaged: TypedContractMethod<
      [parentId: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {result: string[], total: bigint }],
      'view'
    >
    

    
    getAffiliatedParent: TypedContractMethod<
      [childId: string, ],
      [string],
      'view'
    >
    

    
    getAffiliationAudit: TypedContractMethod<
      [childId: string, ],
      [[string, bigint, bigint, string] & {activeParent: string, joinedAt: bigint, detachedAt: bigint, lastDetachedFromParent: string }],
      'view'
    >
    

    
    isAffiliationPending: TypedContractMethod<
      [parentId: string, childId: string, ],
      [boolean],
      'view'
    >
    

    
    leaveAffiliation: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposeAffiliation: TypedContractMethod<
      [parentId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelAffiliationRequest'): TypedContractMethod<
      [parentId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmAffiliation'): TypedContractMethod<
      [childId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'detachAffiliation'): TypedContractMethod<
      [childId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAffiliatedChildren'): TypedContractMethod<
      [parentId: string, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAffiliatedChildrenPaged'): TypedContractMethod<
      [parentId: string, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {result: string[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getAffiliatedParent'): TypedContractMethod<
      [childId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAffiliationAudit'): TypedContractMethod<
      [childId: string, ],
      [[string, bigint, bigint, string] & {activeParent: string, joinedAt: bigint, detachedAt: bigint, lastDetachedFromParent: string }],
      'view'
    >;
getFunction(nameOrSignature: 'isAffiliationPending'): TypedContractMethod<
      [parentId: string, childId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'leaveAffiliation'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposeAffiliation'): TypedContractMethod<
      [parentId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AffiliationConfirmed'): TypedContractEvent<AffiliationConfirmedEvent.InputTuple, AffiliationConfirmedEvent.OutputTuple, AffiliationConfirmedEvent.OutputObject>;
getEvent(key: 'AffiliationDetached'): TypedContractEvent<AffiliationDetachedEvent.InputTuple, AffiliationDetachedEvent.OutputTuple, AffiliationDetachedEvent.OutputObject>;
getEvent(key: 'AffiliationProposed'): TypedContractEvent<AffiliationProposedEvent.InputTuple, AffiliationProposedEvent.OutputTuple, AffiliationProposedEvent.OutputObject>;

    filters: {
      
      'AffiliationConfirmed(string,string,uint256)': TypedContractEvent<AffiliationConfirmedEvent.InputTuple, AffiliationConfirmedEvent.OutputTuple, AffiliationConfirmedEvent.OutputObject>;
      AffiliationConfirmed: TypedContractEvent<AffiliationConfirmedEvent.InputTuple, AffiliationConfirmedEvent.OutputTuple, AffiliationConfirmedEvent.OutputObject>;
    

      'AffiliationDetached(string,string,uint256)': TypedContractEvent<AffiliationDetachedEvent.InputTuple, AffiliationDetachedEvent.OutputTuple, AffiliationDetachedEvent.OutputObject>;
      AffiliationDetached: TypedContractEvent<AffiliationDetachedEvent.InputTuple, AffiliationDetachedEvent.OutputTuple, AffiliationDetachedEvent.OutputObject>;
    

      'AffiliationProposed(string,string,uint256)': TypedContractEvent<AffiliationProposedEvent.InputTuple, AffiliationProposedEvent.OutputTuple, AffiliationProposedEvent.OutputObject>;
      AffiliationProposed: TypedContractEvent<AffiliationProposedEvent.InputTuple, AffiliationProposedEvent.OutputTuple, AffiliationProposedEvent.OutputObject>;
    
    };
  }