/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ODPStatementJournal {
      
    export type StatementStruct = {passportId: string, dataHash: BytesLike, author: AddressLike, authorProfileId: string, kind: BigNumberish, payloadHash: BytesLike, previousId: BigNumberish, publishedAt: BigNumberish}

    export type StatementStructOutput = [passportId: string, dataHash: string, author: string, authorProfileId: string, kind: bigint, payloadHash: string, previousId: bigint, publishedAt: bigint] & {passportId: string, dataHash: string, author: string, authorProfileId: string, kind: bigint, payloadHash: string, previousId: bigint, publishedAt: bigint }
  

    export type LifecycleStruct = {status: BigNumberish, successorId: BigNumberish, reasonHash: BytesLike, changedAt: BigNumberish}

    export type LifecycleStructOutput = [status: bigint, successorId: bigint, reasonHash: string, changedAt: bigint] & {status: bigint, successorId: bigint, reasonHash: string, changedAt: bigint }
  
    }

  export interface ODPStatementJournalInterface extends Interface {
    getFunction(nameOrSignature: "getStatement" | "getStatementsByAuthorPaged" | "getStatementsForPassportPaged" | "odpRegistry" | "publishStatement" | "retractStatement" | "statementCount" | "statementOperations"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "StatementOperationCommitted" | "StatementPublished" | "StatementStatusChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'getStatement', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStatementsByAuthorPaged', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStatementsForPassportPaged', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishStatement', values: [string, BigNumberish, BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'retractStatement', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'statementCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'statementOperations', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getStatement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStatementsByAuthorPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStatementsForPassportPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishStatement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'retractStatement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'statementCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'statementOperations', data: BytesLike): Result;
  }

  
    export namespace StatementOperationCommittedEvent {
      export type InputTuple = [author: AddressLike, operationId: BytesLike, statementId: BigNumberish, digest: BytesLike];
      export type OutputTuple = [author: string, operationId: string, statementId: bigint, digest: string];
      export interface OutputObject {author: string, operationId: string, statementId: bigint, digest: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatementPublishedEvent {
      export type InputTuple = [statementId: BigNumberish, passportId: string, author: AddressLike, passportIdText: string, authorProfileId: string, kind: BigNumberish, dataHash: BytesLike, payloadHash: BytesLike, previousId: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [statementId: bigint, passportId: string, author: string, passportIdText: string, authorProfileId: string, kind: bigint, dataHash: string, payloadHash: string, previousId: bigint, timestamp: bigint];
      export interface OutputObject {statementId: bigint, passportId: string, author: string, passportIdText: string, authorProfileId: string, kind: bigint, dataHash: string, payloadHash: string, previousId: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatementStatusChangedEvent {
      export type InputTuple = [statementId: BigNumberish, status: BigNumberish, successorId: BigNumberish, reasonHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [statementId: bigint, status: bigint, successorId: bigint, reasonHash: string, timestamp: bigint];
      export interface OutputObject {statementId: bigint, status: bigint, successorId: bigint, reasonHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPStatementJournal extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPStatementJournal;
    waitForDeployment(): Promise<this>;

    interface: ODPStatementJournalInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getStatement: TypedContractMethod<
      [id: BigNumberish, ],
      [[ODPStatementJournal.StatementStructOutput, ODPStatementJournal.LifecycleStructOutput]],
      'view'
    >
    

    
    getStatementsByAuthorPaged: TypedContractMethod<
      [author: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[bigint[], bigint]],
      'view'
    >
    

    
    getStatementsForPassportPaged: TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[bigint[], bigint]],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    publishStatement: TypedContractMethod<
      [passportId: string, kind: BigNumberish, payloadHash: BytesLike, previousId: BigNumberish, operationId: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    retractStatement: TypedContractMethod<
      [id: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    statementCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    statementOperations: TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [[string, bigint] & {digest: string, statementId: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getStatement'): TypedContractMethod<
      [id: BigNumberish, ],
      [[ODPStatementJournal.StatementStructOutput, ODPStatementJournal.LifecycleStructOutput]],
      'view'
    >;
getFunction(nameOrSignature: 'getStatementsByAuthorPaged'): TypedContractMethod<
      [author: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[bigint[], bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getStatementsForPassportPaged'): TypedContractMethod<
      [id: string, offset: BigNumberish, limit: BigNumberish, ],
      [[bigint[], bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publishStatement'): TypedContractMethod<
      [passportId: string, kind: BigNumberish, payloadHash: BytesLike, previousId: BigNumberish, operationId: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'retractStatement'): TypedContractMethod<
      [id: BigNumberish, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'statementCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'statementOperations'): TypedContractMethod<
      [arg0: AddressLike, arg1: BytesLike, ],
      [[string, bigint] & {digest: string, statementId: bigint }],
      'view'
    >;

    getEvent(key: 'StatementOperationCommitted'): TypedContractEvent<StatementOperationCommittedEvent.InputTuple, StatementOperationCommittedEvent.OutputTuple, StatementOperationCommittedEvent.OutputObject>;
getEvent(key: 'StatementPublished'): TypedContractEvent<StatementPublishedEvent.InputTuple, StatementPublishedEvent.OutputTuple, StatementPublishedEvent.OutputObject>;
getEvent(key: 'StatementStatusChanged'): TypedContractEvent<StatementStatusChangedEvent.InputTuple, StatementStatusChangedEvent.OutputTuple, StatementStatusChangedEvent.OutputObject>;

    filters: {
      
      'StatementOperationCommitted(address,bytes32,uint256,bytes32)': TypedContractEvent<StatementOperationCommittedEvent.InputTuple, StatementOperationCommittedEvent.OutputTuple, StatementOperationCommittedEvent.OutputObject>;
      StatementOperationCommitted: TypedContractEvent<StatementOperationCommittedEvent.InputTuple, StatementOperationCommittedEvent.OutputTuple, StatementOperationCommittedEvent.OutputObject>;
    

      'StatementPublished(uint256,string,address,string,string,uint8,bytes32,bytes32,uint256,uint256)': TypedContractEvent<StatementPublishedEvent.InputTuple, StatementPublishedEvent.OutputTuple, StatementPublishedEvent.OutputObject>;
      StatementPublished: TypedContractEvent<StatementPublishedEvent.InputTuple, StatementPublishedEvent.OutputTuple, StatementPublishedEvent.OutputObject>;
    

      'StatementStatusChanged(uint256,uint8,uint256,bytes32,uint256)': TypedContractEvent<StatementStatusChangedEvent.InputTuple, StatementStatusChangedEvent.OutputTuple, StatementStatusChangedEvent.OutputObject>;
      StatementStatusChanged: TypedContractEvent<StatementStatusChangedEvent.InputTuple, StatementStatusChangedEvent.OutputTuple, StatementStatusChangedEvent.OutputObject>;
    
    };
  }