/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ODPWalletDocumentAnchorInterface extends Interface {
    getFunction(nameOrSignature: "attestExternalDocument" | "getExternalDocumentAttestation" | "odpRegistry"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ExternalDocumentAttested"): EventFragment;

    encodeFunctionData(functionFragment: 'attestExternalDocument', values: [BytesLike, string]): string;
encodeFunctionData(functionFragment: 'getExternalDocumentAttestation', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'odpRegistry', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attestExternalDocument', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getExternalDocumentAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'odpRegistry', data: BytesLike): Result;
  }

  
    export namespace ExternalDocumentAttestedEvent {
      export type InputTuple = [creatorId: string, creatorIdText: string, attestor: AddressLike, documentHash: BytesLike, documentUri: string, timestamp: BigNumberish];
      export type OutputTuple = [creatorId: string, creatorIdText: string, attestor: string, documentHash: string, documentUri: string, timestamp: bigint];
      export interface OutputObject {creatorId: string, creatorIdText: string, attestor: string, documentHash: string, documentUri: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ODPWalletDocumentAnchor extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPWalletDocumentAnchor;
    waitForDeployment(): Promise<this>;

    interface: ODPWalletDocumentAnchorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attestExternalDocument: TypedContractMethod<
      [documentHash: BytesLike, documentUri: string, ],
      [void],
      'nonpayable'
    >
    

    
    getExternalDocumentAttestation: TypedContractMethod<
      [wallet: AddressLike, documentHash: BytesLike, ],
      [[boolean, string, bigint, string] & {attested: boolean, creatorId: string, timestamp: bigint, documentUri: string }],
      'view'
    >
    

    
    odpRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attestExternalDocument'): TypedContractMethod<
      [documentHash: BytesLike, documentUri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getExternalDocumentAttestation'): TypedContractMethod<
      [wallet: AddressLike, documentHash: BytesLike, ],
      [[boolean, string, bigint, string] & {attested: boolean, creatorId: string, timestamp: bigint, documentUri: string }],
      'view'
    >;
getFunction(nameOrSignature: 'odpRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ExternalDocumentAttested'): TypedContractEvent<ExternalDocumentAttestedEvent.InputTuple, ExternalDocumentAttestedEvent.OutputTuple, ExternalDocumentAttestedEvent.OutputObject>;

    filters: {
      
      'ExternalDocumentAttested(string,string,address,bytes32,string,uint256)': TypedContractEvent<ExternalDocumentAttestedEvent.InputTuple, ExternalDocumentAttestedEvent.OutputTuple, ExternalDocumentAttestedEvent.OutputObject>;
      ExternalDocumentAttested: TypedContractEvent<ExternalDocumentAttestedEvent.InputTuple, ExternalDocumentAttestedEvent.OutputTuple, ExternalDocumentAttestedEvent.OutputObject>;
    
    };
  }